name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running the script file 
      run: |
        echo -- Running Tests ---
        sh ./scripts/run.sh
    - name: Publish the report as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SpecFlowReport
        path: .reports/

    - name: Publishing LivingDoc reports to GitHub pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./public
      
